#!/usr/bin/env bash
set -euo pipefail

# --- helpers ---
log()   { echo "[$(date '+%H:%M:%S')] ✅ $*"; }
warn()  { echo "[$(date '+%H:%M:%S')] ⚠️  $*"; }
abort() { echo "[$(date '+%H:%M:%S')] ❌ $*"; exit 1; }

# ------------------------------------------------------------------------------
# 0. Resolve paths
# ------------------------------------------------------------------------------
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$REPO_DIR/.env"

# --- auto-detect system defaults ---
detect_puid()   { id -u; }
detect_pgid()   { id -g; }
detect_tz() {
    if [ -f /etc/timezone ]; then
        head -1 /etc/timezone
    elif command -v timedatectl &>/dev/null; then
        timedatectl show --property=Timezone --value 2>/dev/null || echo "America/New_York"
    else
        echo "America/New_York"
    fi
}

# ------------------------------------------------------------------------------
# 1. Detect/install Docker + Compose plugin
# ------------------------------------------------------------------------------
log "Checking Docker..."

if ! command -v docker &>/dev/null; then
    log "Docker not found. Installing..."
    if command -v apt-get &>/dev/null; then
        sudo apt-get update -y
        sudo apt-get install -y docker.io docker-compose-v2
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y docker docker-compose-plugin
    elif command -v pacman &>/dev/null; then
        sudo pacman -S --noconfirm docker docker-compose
    else
        abort "Unsupported package manager. Install Docker + Compose manually."
    fi
    sudo systemctl enable --now docker
    sudo usermod -aG docker "$USER" 2>/dev/null || true
    log "Added $USER to docker group — re-login may be needed."
fi

# Compose is required as a plugin or standalone
if ! docker compose version &>/dev/null && ! docker-compose --version &>/dev/null; then
    abort "Docker Compose (plugin or standalone) not found. Install it and re-run."
fi

log "Docker: $(docker --version), Compose: $(docker compose version 2>/dev/null || docker-compose --version)"

# ------------------------------------------------------------------------------
# 2. Create .env with auto-detected values (if not already present)
# ------------------------------------------------------------------------------
if [ -f "$ENV_FILE" ]; then
    log ".env exists — loading..."
    set -a; source "$ENV_FILE"; set +a
else
    log "Auto-generating .env..."
    cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — edit to customize
PUID=$(detect_puid)
PGID=$(detect_pgid)
TZ=$(detect_tz)
MEDIA_BOOKS=/srv/media/books
MEDIA_AUDIO=/srv/media/audiobooks
KAVITA_CONFIG=/srv/config/kavita
ABS_CONFIG=/srv/config/audiobookshelf
KAVITA_PORT=5000
ABS_PORT=13378
EOF
    set -a; source "$ENV_FILE"; set +a
    log "Detected: PUID=${PUID}, PGID=${PGID}, TZ=${TZ}"
fi

# ------------------------------------------------------------------------------
# 3. Create media + config directories with correct ownership
# ------------------------------------------------------------------------------
log "Creating directories..."
sudo mkdir -p "$MEDIA_BOOKS" "$MEDIA_AUDIO" "$KAVITA_CONFIG" "$ABS_CONFIG"
sudo chown -R "${PUID}:${PGID}" "$MEDIA_BOOKS" "$MEDIA_AUDIO" "$KAVITA_CONFIG" "$ABS_CONFIG"
log "Ownership set to ${PUID}:${PGID}"

# ------------------------------------------------------------------------------
# 4. Start services
# ------------------------------------------------------------------------------
log "Starting services with docker compose..."
cd "$REPO_DIR"
docker compose up -d --wait 2>/dev/null || docker compose up -d

# ------------------------------------------------------------------------------
# 5. Print setup URLs
# ------------------------------------------------------------------------------
PI_IP=$(hostname -I 2>/dev/null | awk '{print $1}') || PI_IP="<pi-ip>"

echo ""
echo "============================================="
echo "  Services are up!"
echo ""
echo "  Kavita:         http://${PI_IP}:${KAVITA_PORT:-5000}"
echo "  Audiobookshelf: http://${PI_IP}:${ABS_PORT:-13378}"
echo ""
echo "  Next steps:"
echo "    1. Create admin accounts on each service"
echo "    2. Add libraries and let them scan"
echo "    3. Run scripts/backup.sh to capture a clean baseline"
echo "============================================="
